name: Python Code Check

on:
  push:
    paths:
      - "src/**/*.py"
  pull_request:
    paths:
      - "src/**/*.py"

jobs:
  lint:
    name: Run flake8 on Python files
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8

      - name: Lint code with flake8
        run: |
          flake8 src/ --max-line-length=120 || echo "Linting issues detected, but build will continue."
